baseURL = "https://demo.szclsya.me"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Leo's Field"

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

[params]
  description = "Was *that* life? Well then, once more!"
  author = "Leo Shen"

[taxonomies]
  tag = "tags"
  series = "series"

[languages]
  [languages.en]
    weight = 1
  [languages.zh-cn]
    weight = 2
